version: '3.8'  
services:  
  postgres:  
    container_name: pg_casaolimpo  
    image: postgres  
    restart: always  
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:  
      - "5434:5432"  
  pgadmin:  
    container_name: pgcasaolimpo_container  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:  
      - "8080:80"
    depends_on:
      - postgres
  fastapi:
    build: .
    volumes:
      - ./app:/code/app
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"