"""init

Revision ID: 7013aecf30c7
Revises: a7416fe2086d
Create Date: 2024-07-08 05:34:28.941720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7013aecf30c7'
down_revision: Union[str, None] = 'a7416fe2086d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=True),
    sa.Column('descripcion_categoria', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_categoria_id_categoria'), 'categoria', ['id_categoria'], unique=False)
    op.create_table('marca',
    sa.Column('id_marca', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_marca', sa.String(length=50), nullable=True),
    sa.Column('descripcion_marca', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_marca')
    )
    op.create_index(op.f('ix_marca_id_marca'), 'marca', ['id_marca'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=True),
    sa.Column('descripcion_rol', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_table('prenda',
    sa.Column('id_prenda', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('nombre_prenda', sa.String(length=100), nullable=True),
    sa.Column('descripcion_prenda', sa.String(length=250), nullable=True),
    sa.Column('talla_prenda', sa.String(length=10), nullable=True),
    sa.Column('color_prenda', sa.String(length=30), nullable=True),
    sa.Column('precio_prenda', sa.Numeric(), nullable=True),
    sa.Column('img_prenda', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marca.id_marca'], ),
    sa.PrimaryKeyConstraint('id_prenda')
    )
    op.create_index(op.f('ix_prenda_id_prenda'), 'prenda', ['id_prenda'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('username_usuario', sa.String(length=50), nullable=True),
    sa.Column('clave_usuario', sa.String(length=50), nullable=True),
    sa.Column('email_usuario', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('cedula_cliente', sa.String(length=10), nullable=True),
    sa.Column('primer_nombre_cliente', sa.String(length=50), nullable=True),
    sa.Column('segundo_nombre_cliente', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido_cliente', sa.String(length=50), nullable=True),
    sa.Column('segundo_apellido_cliente', sa.String(length=50), nullable=True),
    sa.Column('direccion_cliente', sa.String(length=100), nullable=True),
    sa.Column('ciudad_cliente', sa.String(length=50), nullable=True),
    sa.Column('correo_cliente', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_index(op.f('ix_cliente_id_cliente'), 'cliente', ['id_cliente'], unique=False)
    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    op.create_index(op.f('ix_carrito_id_carrito'), 'carrito', ['id_carrito'], unique=False)
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=True),
    sa.Column('total_venta', sa.Numeric(), nullable=True),
    sa.Column('metodo_pago_venta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_index(op.f('ix_venta_id_venta'), 'venta', ['id_venta'], unique=False)
    op.create_table('carrito_prenda',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_prenda', sa.Integer(), nullable=False),
    sa.Column('cantidad_carrito_prenda', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id_carrito'], ),
    sa.ForeignKeyConstraint(['id_prenda'], ['prenda.id_prenda'], ),
    sa.PrimaryKeyConstraint('id_carrito', 'id_prenda')
    )
    op.create_table('detalle_venta',
    sa.Column('id_detalle_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_prenda', sa.Integer(), nullable=False),
    sa.Column('cantidad_detalle_venta', sa.Integer(), nullable=True),
    sa.Column('total_detalle_venta', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id_prenda'], ['prenda.id_prenda'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_detalle_venta')
    )
    op.create_index(op.f('ix_detalle_venta_id_detalle_venta'), 'detalle_venta', ['id_detalle_venta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_venta_id_detalle_venta'), table_name='detalle_venta')
    op.drop_table('detalle_venta')
    op.drop_table('carrito_prenda')
    op.drop_index(op.f('ix_venta_id_venta'), table_name='venta')
    op.drop_table('venta')
    op.drop_index(op.f('ix_carrito_id_carrito'), table_name='carrito')
    op.drop_table('carrito')
    op.drop_index(op.f('ix_cliente_id_cliente'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_prenda_id_prenda'), table_name='prenda')
    op.drop_table('prenda')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_marca_id_marca'), table_name='marca')
    op.drop_table('marca')
    op.drop_index(op.f('ix_categoria_id_categoria'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
