"""Agregar stock en prendas

Revision ID: 7351f20d9ab8
Revises: 73c917eec130
Create Date: 2025-01-16 16:37:41.184094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7351f20d9ab8'
down_revision: Union[str, None] = '73c917eec130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prenda', sa.Column('stock_prenda', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prenda', 'stock_prenda')
    # ### end Alembic commands ###
