"""2F Auth changes

Revision ID: bb9ddedbe29e
Revises: c2520eb0f41b
Create Date: 2025-01-22 02:18:09.459854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9ddedbe29e'
down_revision: Union[str, None] = 'c2520eb0f41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('two_fa_code', sa.String(length=6), nullable=True))
    op.add_column('usuario', sa.Column('two_fa_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'two_fa_expiration')
    op.drop_column('usuario', 'two_fa_code')
    # ### end Alembic commands ###
