"""Agregar valor por defecto a stock_prenda

Revision ID: c2520eb0f41b
Revises: 7351f20d9ab8
Create Date: 2025-01-16 16:51:58.355718

"""
from typing import Sequence, Union
from sqlalchemy.sql.sqltypes import Integer
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2520eb0f41b'
down_revision: Union[str, None] = '7351f20d9ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prenda", "stock_prenda", existing_type=Integer, server_default="0")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
